name: Test Python Package

on: workflow_dispatch
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    # - name: Lint with pylint
    #   run: |
    #     poetry run pylint ./chatnerd
    - name: Format check with black
      run: |
        poetry run black --check ./chatnerd
    - name: Check for unused imports with autoflake
      run: |
        poetry run autoflake --check-only --remove-unused-variables --remove-all-unused-imports --recursive ./chatnerd 
